---
- hosts: all
  sudo: true
  roles:
    - role: znzj.rbenv
      rbenv_ruby_version: 2.2.1
  tasks:
    - apt_repository: repo=ppa:chris-lea/node.js
    - apt: update_cache=yes

    - apt: name=git-core
    - apt: name=curl
    - apt: name=zlib1g-dev
    - apt: name=build-essential
    - apt: name=libssl-dev
    - apt: name=libreadline-dev
    - apt: name=libyaml-dev
    - apt: name=libsqlite3-dev
    - apt: name=sqlite3
    - apt: name=libxml2-dev
    - apt: name=libxslt1-dev
    - apt: name=libcurl4-openssl-dev
    - apt: name=python-software-properties
    - apt: name=libffi-dev

    - apt: name=nodejs

    - gem: name=bundler